<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="admin.aspx.cs" Inherits="WebApplication2.admin" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Administration</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:GridView runat="server" ID="mydatagridview" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="d_id" 
            DataSourceID="SqlDataSource1" OnSelectedIndexChanged="mydatagridview_SelectedIndexChanged"
            EnableModelValidation="true"
            >
            <Columns>
                <asp:BoundField DataField="d_id" HeaderText="d_id" InsertVisible="False" ReadOnly="True" SortExpression="d_id" />
                <asp:BoundField DataField="fname" HeaderText="fname" SortExpression="fname" />
                <asp:BoundField DataField="lname" HeaderText="lname" SortExpression="lname" />
                <asp:BoundField DataField="Addrss" HeaderText="Addrss" SortExpression="Addrss" />
                <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
                <asp:BoundField DataField="neighbourhood" HeaderText="neighbourhood" SortExpression="neighbourhood" />
                <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                <asp:BoundField DataField="speciality" HeaderText="speciality" SortExpression="speciality" />
                <asp:BoundField DataField="phone" HeaderText="phone" SortExpression="phone" />
                <asp:BoundField DataField="pswD" HeaderText="pswD" SortExpression="pswD" />
            </Columns>
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:doctorsDBConnectionString %>" 
            SelectCommand="SELECT * FROM [doctors]"
            UpdateCommand="update [doctors] set [fname]=@fname, [lname]=@lname, [Addrss]=@Addrss, [City]=@City,
            [neighbourhood]=@neighbourhood, [email]=@email, [speciality]=@speciality, [phone]=@phone, [pswD]=@pswD
            where [d_id]=@d_id"
            DeleteCommand="delete from [doctors] where [d_id]=@d_id" OnSelecting="SqlDataSource1_Selecting">

            <UpdateParameters>
                <asp:Parameter Name="fname"/>
                <asp:Parameter Name="lname"/>
                <asp:Parameter Name="Addrss"/>
                <asp:Parameter Name="City"/>
                <asp:Parameter Name="neighbourhood"/>
                <asp:Parameter Name="email"/>
                <asp:Parameter Name="speciality"/>
                <asp:Parameter Name="phone"/>
                <asp:Parameter Name="pswD"/>
                <asp:Parameter Name="d_id"/>
            </UpdateParameters>
        </asp:SqlDataSource>

        <asp:Label ID="Label1" runat="server" Text="First name: "></asp:Label>
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <br />
        <asp:Label ID="Label2" runat="server" Text="Last Name: "></asp:Label>
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
        <br />
        <asp:Label ID="Label3" runat="server" Text="Address: "></asp:Label>
        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
        <br />
        <asp:Label ID="Label4" runat="server" Text="City: "></asp:Label>
        <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
        <br />
        <asp:Label ID="Label5" runat="server" Text="Neighbourhood: "></asp:Label>
        <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
        <br />
        <asp:Label ID="Label6" runat="server" Text="E-mail: "></asp:Label>
        <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox>
        <br />
        <asp:Label ID="Label7" runat="server" Text="Speciality: "></asp:Label>
        <asp:TextBox ID="TextBox7" runat="server"></asp:TextBox>
        <br />
        <asp:Label ID="Label8" runat="server" Text="Phone: "></asp:Label>
        <asp:TextBox ID="TextBox8" runat="server"></asp:TextBox>
        <br />
        <asp:Label ID="Label9" runat="server" Text="Password: "></asp:Label>
        <asp:TextBox ID="TextBox9" runat="server"></asp:TextBox>
        <br />
        <asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Insert" />
        <br />

    </div>
    </form>
</body>
</html>
